### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by TomTomZoe**

### CODE REVIEW

**Comment by TomTomZoe** [comment]
I didn't see that DIDoS had already done a German translation, yesterday when I set myself the translation task, it wasn't available yet ;-)

However, I cannot agree at all with his correction from degradation to wear and tear. Nobody in Germany speaks of battery wear, the term battery degradation is a standing common term.

**Comment by SamuelBrucksch** [comment]
Let's merge https://github.com/Iternio-Planning-AB/abrp-translations/pull/826 first as we already discussed it there and see what else remains in here.

**Comment by SamuelBrucksch** [comment]
@TomTomZoe kannst du bitte updaten und schauen, ob noch was neues oder verbesserungswürdiges dabei ist? Danke!

**Comment by TomTomZoe** [comment]
As I meantioned two weeks ago, all phrases where already translated and discussed, so mine can be closed.

**Pull request closed without merging**
